### ISSUE TITLE
toots.hwl.li, Stux, my pissy response to him, context, my blocklist spreadsheet.

### ISSUE THREAD

**Issue by jwbjnwolf** [greyhat-academy/lists.d#34]
Hi, Jase here who got pissy at Stux back at the end of May, re about: https://mstdn.social/@kkarhan/110444607555134799

..from back when Stux pulled my instance for me getting pissy at him in that report at the end of May, which I'd like to give the context on why I got so mad at Stux getting mad to his 100k+ followers (meant to say followers in that report rather than fans.. that did sound assy) about that I'd blocked him.

https://toots.hwl.li/@jase/110572122255495642
https://toots.hwl.li/@jase/110572373781494428

And a later post I did on the Universeodon thing in which I too suspended now that my one connection from there had deleted:
https://toots.hwl.li/@jase/110584086163472311

That's the context I mainly want to share but since that interaction was about more than *just* that, and I do not want to put in a massive post in an issue to you coming across as a pile on, I've posted here, as well with appropriate CWs:

https://toots.hwl.li/@jase/110600456494671065

Posted in response to my private account splitting the first linked thread so it doesn't enter folks feeds.

I didn't want to back then because well it was just seemingly just *me* and I was coming to terms of all this, and my context was a complete mess. But I want to now share the context that I put it together, for you to make an informed decision on what you want to make of all this.

Edit: sorry then, wasn't my intent to be spam. I did deem this relevant since this was brought up. Just intended to share some context since it's far from just me.

**Comment by kkarhan** [comment]
@jwbjnwolf please feel free to [contact me in person if you want to](http://karhan.guru) and [please use gists for your private posts](https://gist.github.com/) that have no relevance to [this specific project](https://github.com/greyhat-academy/lists.d).

Don't spam into the issues of this project, as I'd otherwise be obligated to ban you and potentially restrict issues and pull requests if you - or anyone else - when trying to attempt to circumvent said ban, cuz [I don't have time for this shit](https://github.com/kkarhan/misc-stuff/blob/main/publications/statements/20221110/serial-harassers.md)!

Thanks for your understanding.

PS: You ain't banned, but consider this as a warning!
