### ISSUE TITLE
Blocking BlueSky for CSAM & Neonazis

### ISSUE THREAD

**Issue by kkarhan** [greyhat-academy/lists.d#35]
Based off [this proposal](https://github.com/bluesky-social/proposals/tree/main/0002-labeling-and-moderation-controls), specifically [Accepting CSAM](https://github.com/bluesky-social/proposals/blob/751dc2781dfe7680b63167e758fce28e1ab637ff/0002-labeling-and-moderation-controls/README.md?plain=1#L91), I'll add it to the [activitypub.domains.block.list.tsv](https://github.com/greyhat-academy/lists.d/blob/main/activitypub.domains.block.list.tsv).

CSAM is criminalized for good reasons, as violations of one's sexual autonomy, espechally to minors that are legally incapable to consent, is absolutely unacceptable and anyone who considers to "debate that" is noone I'll interact with!

**Comment by kkarhan** [comment]
In terms of Domains, this will be `bsky.app` & `bsky.social` ...

**Comment by kkarhan** [comment]
Has been completed with [this commit]:
https://github.com/greyhat-academy/lists.d/commit/7c77ff33b04762210a9780660caa0fb856d8ea7d

**Comment by intrnl** [comment]
csam was a label clients can use to force hide posts that contains it while it's being purged, also to indicate to others to also delete them (in case of proxies, or anyone running a monitoring service)

csam was not a label to mean "bluesky accepts csam materials spreading around"

in any case, [the actual implemented proposal no longer has csam as a label](https://github.com/bluesky-social/atproto/blob/462de219eedc3c862ca6f88ec130d55c2f6af954/packages/api/docs/labels.md), it's now part of the generic !hide label

**Comment by intrnl** [comment]
the neo-nazis bit is funny though because there's nothing here actually proving that "bluesky has nazis", so tacking that as a reasoning is definitely a Choice

bluesky moderation team bans nazis, the content filtering for "hate group" was more to hide any iconography of it in case anyone was talking about it in a serious depth (having a deep conversation around hate speech groups) and was not intended to "sweep the nazis under the rug and let users pretend they don't exist"

in any case, [it's also been renamed to "hate group iconography" to make it clear that's the case](https://github.com/bluesky-social/social-app/commit/831b367eb952af464fdfebcefb355b0cadaea359)

**Comment by kkarhan** [comment]
I'll consider removing BlueSky once evidence has been posted that said 
reasons do not apply anymore which is in line with the current standards 
for removing listings.

Please open up a new issue in that case and only reference this one as 
this is a closed issue!

Thanks.
