### ISSUE TITLE
Transphobic & Racist Instances

### ISSUE THREAD

**Issue by RoxyBoxxy** [greyhat-academy/lists.d#43]
HOSTS:
crlf.ninja
seal.cafe
anthro.cc

Links:  https://anthro.cc/notes/9jixg6sgctphd6tp
https://seal.cafe/notice/AZfy25kgQBcup2r2K8
https://crlf.ninja/objects/2c8ec46f-5fe9-44e0-bcca-358c15fe71e8

**Comment by RoxyBoxxy** [comment]
another place https://poster.place/notice/AZfzSdRTZMiJ3y18iW

**Comment by kkarhan** [comment]
@RoxyBoxxy thx for your submissions... 

I'll have a quick look at them...

**Comment by kkarhan** [comment]
# Investigation:
---

1. The [Post from anthro.cc](https://anthro.cc/notes/9jixg6sgctphd6tp) give me a 404 and [the entire domain seems bust](https://anthro.cc/)... 

2. The [Post from seal.cafe](https://seal.cafe/notice/AZfy25kgQBcup2r2K8) is obvious even if the domain wasn't a straight-up hint at [Sealioning](https://en.wikipedia.org/wiki/Sealioning)

3. The [Post from crlf.ninja](https://crlf.ninja/objects/2c8ec46f-5fe9-44e0-bcca-358c15fe71e8) just gave me a JSON dump and no direct post, but I [could see the attachment that shows that said instance does in fact endorse said users' hatespeech](https://media.crlf.ninja/8e2d1a4f38f8894303bfcdb19904cebc1b1c69b20859ba86fc2b0f0b13aa25e3.png) which I [then found on said users media tab in their profile](https://crlf.ninja/notice/AZfyMkCrmoewX2N64e).

4. The [poster.place post already was obvious on it's own](https://poster.place/notice/AZfzSdRTZMiJ3y18iW).

5. The [banner they have on their website using the word "troons"](https://poster.place/media/89cd5cd00644671e90c2feba16164f719fb24038fe8e7eaf856a68320dc08b40.gif) made it clear that this just just a site to circumvent [the entries for KiwiFarms on the blocklist](https://github.com/greyhat-academy/lists.d/blob/5c730afeb5a51756b19cd143383afbf391340337/activitypub.domains.block.list.tsv#L25).

--- 
# Conclusion: 
I thus will add all these - except anthro.cc since it's 404'ing on me -  to [activitypub.domains.block.list.tsv](https://github.com/greyhat-academy/lists.d/blob/main/activitypub.domains.block.list.tsv).

[crlf.ninja is already on the blocklist](https://github.com/greyhat-academy/lists.d/blob/5c730afeb5a51756b19cd143383afbf391340337/activitypub.domains.block.list.tsv#L59).

Unless there's something needed to be added from your end I'll close this issue once the change has been added to the main branch.

**Comment by kkarhan** [comment]
Done.
Thx @RoxyBoxxy for your submission.

Feel free to make any reports anytime...

**Comment by RoxyBoxxy** [comment]
> Done. Thx @RoxyBoxxy for your submission.
> 
> Feel free to make any reports anytime...

Thank you, anthro.cc its working on my end, maybe they have blocked your ip, i can provide screenshots

**Comment by kkarhan** [comment]
Let me check...

**Comment by kkarhan** [comment]
Okay, sorry for me taking some time...

Not only does anthro.cc do the obnoxious and ableist tactic of forcing JavaScript to load the website, so it blocked Tor Browser.

But it's my fault that I could not see it since their website is hosted by [known Rogue ISP TerraHost](https://github.com/greyhat-academy/lists.d/blob/4e33846cbec12be0d5f92164c3e3783d9321e1d8/drop.ipv4.block.list.tsv#L160C15-L160C15) which has been on the [DROP Blocklist](https://github.com/greyhat-academy/lists.d/blob/4e33846cbec12be0d5f92164c3e3783d9321e1d8/drop.ipv4.block.list.tsv#L141) for supporting KiwiFarms.

![Bildschirmfoto vom 2023-09-13 06-15-05](https://github.com/greyhat-academy/lists.d/assets/30401796/faf23277-30b0-47d7-a55a-d72a224d210c)


After all, I do use the blocklists I maintain myself both privately and at work... 

I'll add it to the list as well as I can't be certain that people would use the {DROP Blocklist](https://github.com/greyhat-academy/lists.d/blob/main/drop.ipv4.block.list.tsv) on their ActivityPub Servers as those have [different goals in mind](https://github.com/greyhat-academy/lists.d/blob/main/drop.ipv4.block.list.tsv)...

**Comment by kkarhan** [comment]
I guess that's done now.

@RoxyBoxxy If you find any other domains, please feel free to open up a new issue...

To automatically import and update it, feel free let your server['s Admin*s] pull it from the following URL automatically:
https://raw.githubusercontent.com/greyhat-academy/lists.d/main/activitypub.domains.block.list.tsv

Thx again for your time and patience.

**Comment by virtadpt** [comment]
> Thank you, anthro.cc its working on my end, maybe they have blocked your ip, i can provide screenshots

I can see it from home and from work.
