### ISSUE TITLE
Defamation, Abuse, and Revenge Blocking

### ISSUE THREAD

**Issue by lexi-the-cute** [greyhat-academy/lists.d#44]
A couple of instances have willingly defamed trans women like me for daring to question the legitimacy of their claims against other trans women.

The two main instances I have issues with are:

* mastodon.art
* ubiqueros.com

Many people have defended my character including https://portend.place/notice/AZiATqKMiEcusFpS40 (you may have to paste this into the search bar of your instance to read it) and https://mastodon.social/@TheGoodSpace/111052271194393071.

You can also ask many, many instance admins such as the ones who run tech.lgbt and tooters.org. Also since you've been following me from long before the bad space defamed me, you know what kind of person I am.

I know abuse when I see it and I would link the post where Ro questioned one of my follower's mental capacity, but I didn't ask her permission if she wanted to publicly be linked to this, so I'm not posting it, but you can ask me by DM as I did ask for permission to share this with trusted people.

I don't care that they revenge blocked me, I just care about being defamed when I never did anything wrong

**Comment by kkarhan** [comment]
### 1. I do agree with your assessment.

My only question at this point is however, if you have reported said posts and instead of moderators taking them seriously they've chosen to instead ridicule if not started "shooting the messenger" [like in this case](https://github.com/greyhat-academy/lists.d/issues/43)... 

OFC if you can attach evidence that these attempts would've been fruitless [i.e. admins / moderators engaging in said actions themselves] then that would be also sufficient evidence.

---

### However...
Before I'd just blindly add these I've to act in due diligence, as not doing so would not only jeopardize the integrity but also open up the floodgates for being just another battleground for "fediverse drama" and not an instance that aims to provide as accurate info as possible and not do [overblocking like some other places](https://wiki.todon.eu/todon/domainblocks)...

**Comment by lexi-the-cute** [comment]
Ro from ubiqueros is both the admin of ubiqueros.com and the owner of thebad.space. Here's an administrative post he made. https://ubiqueros.com/notes/9jknj59gr8

Below is a screenshot of the server info of ubiqueros.com:
![Screenshot_20230913_051943](https://github.com/greyhat-academy/lists.d/assets/120563837/b1eaf179-f5bf-41cc-b3bc-2776b0fd0292)

Here's an instance of Ro scoffing at the idea of the good space which is a site dedicated to actually evaluating the legitimacy of every entry on the bad space. https://ubiqueros.com/notes/9jkjz7iz2g

Here's just one of the hundreds if not thousands of responses from the past few days where Ro has shown nothing but insulting people who question the project https://ubiqueros.com/notes/9jk1vdkja8

Especially since so many many instances on the list are LGBT and all you have to do is question the legitimacy of even one of the moderation decisions like how I defended AnarchoNina and now 3 instances have me blocked. One being mastodon.art and the other being rage.love (where the rage.love admin had previously been forced to admit to defaming AnarchoNina).

Also, if you look at my entry on the good place, you'll see the person explaining how I'm innocent, yet here I am on this list being defamed. https://mastodon.art/about

All because I questioned the moderation decision of WelshPixie

**Comment by kkarhan** [comment]
Thanks for bringing this to light...

I'll add said sites to the list.

**Comment by lexi-the-cute** [comment]
Thanks!

**Comment by kkarhan** [comment]
Done.

Feel free to open a new issue for other domains if they pop up.
