### ISSUE TITLE
social.mooneyed.de

### ISSUE THREAD

**Issue by kromonos** [greyhat-academy/lists.d#52]
Wenn du nicht Teil der Ermittlungen der Kriminalpolizei, Abteilung Staatsschutz, die gerade gegen Schratze laufen, werden willst, empfehle ich dir dringend, dem Eintrag über social.mooneyed.de zu löschen. Ansonsten liegt ein Verstoß gegen § 185 bis 187 StGB vor

**Comment by kromonos** [comment]
If you would rather not become part of the criminal investigation currently ongoing against Schratze, due to the false accusations of Nazism and fascism against my person, I strongly recommend that you delete the entry about social.mooneyed.de. Otherwise, you are in violation of § 185 to 187 StGB and will be part of!  

As you are resident in Germany, you will be held accountable accordingly. Your data has been saved and will be submitted to the criminal direction Karlsruhe in time.

![image](https://github.com/greyhat-academy/lists.d/assets/1553902/dcac9738-a9e4-4e2f-a9bc-45679525a7d1)

**Comment by kkarhan** [comment]
I consider [this](https://github.com/greyhat-academy/lists.d/issues/52#issue-2131653148) as threat and harrassment and will not only contact GitHub Support but also consider pressing charges at the police and provide them the entire issue as evidence.

I'll expect you to apologize instead, since your behaviour in the form of words and actions are a not just counterproductive but exemplify why your domain has been listed.

I'll reconsider delisting once the reasons for the listing have been removed.
See [Troubleshooting in the README](https://github.com/greyhat-academy/lists.d?tab=readme-ov-file#troubleshooting).

**Comment by kkarhan** [comment]
For the record, said [attempts of blackmail](https://github.com/greyhat-academy/lists.d/issues/52#issue-2131653148) have failed.
